### ISSUE TITLE
Crash with Betweenlands

### ISSUE THREAD

**Issue by psymin** [lumien231/Simple-Dimensions#14]
It appears that Simple-Dimensions and The Betweenlands don't play nicely together.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/8/18 11:23 AM
Description: Exception in server tick loop

java.lang.RuntimeException: World New Dimension (lumien.simpledimensions.server.WorldProviderSimpleDimension) does not have BetweenlandsWorldStorage capability
	at thebetweenlands.common.world.storage.BetweenlandsWorldStorage.forWorld(BetweenlandsWorldStorage.java:222)
	at thebetweenlands.common.handler.EnvironmentEventHandler.onWorldTick(EnvironmentEventHandler.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_109_EnvironmentEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.12.12-gentoo
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2174878504 bytes (2074 MB) / 3505389568 bytes (3343 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                                  | Signature                                |
	|:--------- |:-------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.2.2611-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2611 | forge-1.12.2-14.23.2.2611-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | justenoughdimensions | 1.5.5        | justenoughdimensions-1.12.1-1.5.5.jar   | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | simpledimensions     | 1.3.1        | SimpleDimensions-MC1.12-1.3.1.jar       | None                                     |
	| UCHIJAAAA | thebetweenlands      | 3.3.4        | TheBetweenlands-3.3.4-universal.jar     | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TheCyberBrick** [comment]
Similar problem to https://github.com/lumien231/Simple-Dimensions/issues/12 and solution would be to call `super.init()` (or at least `initCapabilities` in this case) as suggested in https://github.com/TeamTwilight/twilightforest/issues/334#issuecomment-344767981

**Comment by ikkerens** [comment]
Yup, PR #13 should fix this, I've included a jar with this fixed there. Or you could build it yourself from my fork.

**Comment by P3rf3ctXZer0** [comment]
@ikkerens can you also fix the api overwriting dimensions? I noticed when I create a dimension is overwriting the second one even on patch jar. Maybe you should just fork the mod because the maintainer isn't interested in maintaining. This is very sad because like Dimensional Doors this mod is legendary.
